require('dotenv').config();
const cookieParser = require('cookie-parser');
const expressLayouts = require('express-ejs-layouts');
const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;
const methodOverride = require('method-override');
const connectDB = require('./API/db/connect');
connectDB();
app.use(express.urlencoded({extended: true}));
app.use(express.json());
app.use(cookieParser());
app.use(methodOverride('_method'));
app.use(expressLayouts);
app.use(express.static('public'));
app.set('layout', './views/layout/primary');
app.set('view engine', 'ejs');
app.use('/', require('./API/routes/index'));
app.listen(PORT, () => console.log(`Server is running on PORT: ${PORT}`));
