### GET TEST ROUTE
GET http://localhost:3000/test HTTP/1.1

### POST NEWPREDICTION ROUTE
POST http://localhost:3000/predictions HTTP/1.1
Content-Type: application/json
{
    "userQuery": "Example?",
    "ballAnswer": "Answer.",
}